976
WUUS54 KMOB 031346
SVRMOB
ALC035-039-031430-
/O.NEW.KMOB.SV.W.0077.230403T1346Z-230403T1430Z/

BULLETIN - IMMEDIATE BROADCAST REQUESTED
Severe Thunderstorm Warning
National Weather Service Mobile AL
846 AM CDT Mon Apr 3 2023

The National Weather Service in Mobile has issued a

* Severe Thunderstorm Warning for...
  Conecuh County in south central Alabama...
  Northwestern Covington County in south central Alabama...

* Until 930 AM CDT.

* At 846 AM CDT, a severe thunderstorm was located 4 miles northwest
  of I65 And US 84, or 6 miles northwest of Evergreen, moving east at
  40 mph.

  HAZARD...60 mph wind gusts and nickel size hail.

  SOURCE...Radar indicated.

  IMPACT...Expect damage to roofs, siding, and trees.

* Locations impacted include...
  Andalusia, Evergreen, River Falls, Red Level, Repton, Heath, Gantt
  and I65 And US 84.

PRECAUTIONARY/PREPAREDNESS ACTIONS...

A Tornado Watch remains in effect until 1100 AM CDT for south central
Alabama.

For your protection move to an interior room on the lowest floor of a
building.

A Tornado Watch remains in effect until 1100 AM CDT for south central
Alabama.

&&

LAT...LON 3123 8649 3119 8666 3123 8677 3126 8677
      3126 8687 3140 8728 3145 8723 3146 8720
      3155 8716 3165 8708 3159 8689 3155 8687
      3153 8684 3152 8665 3145 8641 3135 8640
TIME...MOT...LOC 1346Z 285DEG 37KT 3147 8706

HAIL THREAT...RADAR INDICATED
MAX HAIL SIZE...0.88 IN
WIND THREAT...RADAR INDICATED
MAX WIND GUST...60 MPH

$$

Black