
827 
WWUS54 KEWX 210517 RRA
SVSEWX

Severe Weather Statement
National Weather Service Austin/San Antonio TX
1217 AM CDT Fri Apr 21 2023

TXC055-177-187-210545-
/O.CON.KEWX.SV.W.0086.000000T0000Z-230421T0545Z/
Caldwell TX-Guadalupe TX-Gonzales TX-
1217 AM CDT Fri Apr 21 2023

...A SEVERE THUNDERSTORM WARNING REMAINS IN EFFECT UNTIL 1245 AM CDT
FOR SOUTHERN CALDWELL...SOUTHEASTERN GUADALUPE AND GONZALES
COUNTIES...

At 1217 AM CDT, severe thunderstorms were located along a line
extending from near Luling to near Palmeto State Park to 7 miles
north of Pandora, moving southeast at 35 mph.

HAZARD...60 mph wind gusts and half dollar size hail.

SOURCE...Radar indicated.

IMPACT...Hail damage to vehicles is expected. Expect wind damage to 
         roofs, siding, and trees.

Locations impacted include...
Gonzales, Luling, Nixon, Kingsbury, Smiley, Fentress, Palmeto State
Park, Leesville, Joliet, Oak Forest, Stairtown, Sample, Belmont,
Wrightsboro, Cost, McNeil, Thompsonville, Ottine, Hamon and Bebe.

PRECAUTIONARY/PREPAREDNESS ACTIONS...

Prepare immediately for large hail and damaging winds. People outside
should move to a shelter, inside a strong building and away from
windows.

Continuous cloud to ground lightning is occurring with these storms.
Move indoors immediately. Lightning is one of nature's leading
killers. Remember, if you can hear thunder, you are close enough to
be struck by lightning.

Torrential rainfall is occurring with these storms, and may lead to
flash flooding. Do not drive your vehicle through flooded roadways.

&&

LAT...LON 2938 9795 2958 9775 2978 9778 2973 9731
      2937 9731 2913 9759 2927 9778 2935 9786
      2938 9784
TIME...MOT...LOC 0517Z 305DEG 31KT 2972 9770 2954 9763 2935 9787 

HAIL THREAT...RADAR INDICATED
MAX HAIL SIZE...1.25 IN
WIND THREAT...RADAR INDICATED
MAX WIND GUST...60 MPH

$$

BRADY


======================================================================

463 
WWUS54 KEWX 210502
SVSEWX

Severe Weather Statement
National Weather Service Austin/San Antonio TX
1202 AM CDT Fri Apr 21 2023

TXC055-177-187-210545-
/O.CON.KEWX.SV.W.0086.000000T0000Z-230421T0545Z/
Caldwell TX-Guadalupe TX-Gonzales TX-
1202 AM CDT Fri Apr 21 2023

...A SEVERE THUNDERSTORM WARNING REMAINS IN EFFECT UNTIL 1245 AM CDT
FOR SOUTHERN CALDWELL...GUADALUPE AND GONZALES COUNTIES...

At 1202 AM CDT, severe thunderstorms were located along a line
extending from near Staples to near Kingsbury to 9 miles southeast of
New Berlin, moving southeast at 25 mph.

HAZARD...Golf ball size hail and 70 mph wind gusts.

SOURCE...Radar indicated.

IMPACT...People and animals outdoors will be injured. Expect hail 
         damage to roofs, siding, windows, and vehicles. Expect 
         considerable tree damage. Wind damage is also likely to 
         mobile homes, roofs, and outbuildings.

Locations impacted include...
San Marcos, Seguin, Gonzales, Luling, Nixon, Martindale, Kingsbury,
Smiley, Staples, Fentress, Palmeto State Park, Zorn, Geronimo,
Brownsboro, Leesville, Joliet, Oak Forest, Belmont, Cost and McNeil.

PRECAUTIONARY/PREPAREDNESS ACTIONS...

Prepare immediately for large hail and damaging winds. People outside
should move to a shelter, inside a strong building and away from
windows.

Continuous cloud to ground lightning is occurring with these storms.
Move indoors immediately. Lightning is one of nature's leading
killers. Remember, if you can hear thunder, you are close enough to
be struck by lightning.

Torrential rainfall is occurring with these storms, and may lead to
flash flooding. Do not drive your vehicle through flooded roadways.

&&

LAT...LON 2913 9759 2927 9778 2935 9786 2938 9784
      2938 9794 2947 9807 2966 9792 2978 9797
      2985 9789 2982 9739 2982 9735 2978 9731
      2937 9731
TIME...MOT...LOC 0502Z 301DEG 23KT 2979 9788 2962 9775 2941 9797 

THUNDERSTORM DAMAGE THREAT...CONSIDERABLE
HAIL THREAT...RADAR INDICATED
MAX HAIL SIZE...1.75 IN
WIND THREAT...RADAR INDICATED
MAX WIND GUST...70 MPH

$$

BRADY


======================================================================

730 
WWUS54 KEWX 210453
SVSEWX

Severe Weather Statement
National Weather Service Austin/San Antonio TX
1153 PM CDT Thu Apr 20 2023

TXC209-210503-
/O.CAN.KEWX.SV.W.0086.000000T0000Z-230421T0545Z/
Hays TX-
1153 PM CDT Thu Apr 20 2023

...THE SEVERE THUNDERSTORM WARNING FOR SOUTH CENTRAL HAYS COUNTY IS
CANCELLED...

The storms which prompted the warning have moved out of the warned 
area. Therefore, the warning has been cancelled.

A Severe Thunderstorm Watch remains in effect until 200 AM CDT for
south central Texas.

LAT...LON 2913 9759 2927 9778 2935 9786 2938 9784
      2938 9794 2947 9807 2966 9792 2978 9797
      2985 9789 2982 9739 2982 9735 2978 9731
      2937 9731
TIME...MOT...LOC 0453Z 302DEG 24KT 2982 9793 2964 9779 2944 9802 

$$

TXC055-177-187-210545-
/O.CON.KEWX.SV.W.0086.000000T0000Z-230421T0545Z/
Caldwell TX-Guadalupe TX-Gonzales TX-
1153 PM CDT Thu Apr 20 2023

...A SEVERE THUNDERSTORM WARNING REMAINS IN EFFECT UNTIL 1245 AM CDT
FOR SOUTHERN CALDWELL...GUADALUPE AND GONZALES COUNTIES...

At 1153 PM CDT, severe thunderstorms were located along a line
extending from near San Marcos to Kingsbury to near New Berlin,
moving southeast at 30 mph.

HAZARD...70 mph wind gusts and ping pong ball size hail.

SOURCE...Radar indicated.

IMPACT...People and animals outdoors will be injured. Expect hail 
         damage to roofs, siding, windows, and vehicles. Expect 
         considerable tree damage. Wind damage is also likely to 
         mobile homes, roofs, and outbuildings.

Locations impacted include...
San Marcos, Seguin, Gonzales, Luling, Nixon, Martindale, Kingsbury,
Smiley, Staples, Fentress, Palmeto State Park, Zorn, Geronimo,
Brownsboro, Leesville, Joliet, Oak Forest, Belmont, Cost and McNeil.

PRECAUTIONARY/PREPAREDNESS ACTIONS...

Prepare immediately for large hail and damaging winds. People outside
should move to a shelter, inside a strong building and away from
windows.

Continuous cloud to ground lightning is occurring with these storms.
Move indoors immediately. Lightning is one of nature's leading
killers. Remember, if you can hear thunder, you are close enough to
be struck by lightning.

Torrential rainfall is occurring with these storms, and may lead to
flash flooding. Do not drive your vehicle through flooded roadways.

&&

LAT...LON 2913 9759 2927 9778 2935 9786 2938 9784
      2938 9794 2947 9807 2966 9792 2978 9797
      2985 9789 2982 9739 2982 9735 2978 9731
      2937 9731
TIME...MOT...LOC 0453Z 302DEG 24KT 2982 9793 2964 9779 2944 9802 

THUNDERSTORM DAMAGE THREAT...CONSIDERABLE
HAIL THREAT...RADAR INDICATED
MAX HAIL SIZE...1.50 IN
WIND THREAT...RADAR INDICATED
MAX WIND GUST...70 MPH

$$

BRADY


======================================================================

934 
WUUS54 KEWX 210443
SVREWX
TXC055-177-187-209-210545-
/O.NEW.KEWX.SV.W.0086.230421T0443Z-230421T0545Z/

BULLETIN - IMMEDIATE BROADCAST REQUESTED
Severe Thunderstorm Warning
National Weather Service Austin/San Antonio TX
1143 PM CDT Thu Apr 20 2023

The National Weather Service in Austin San Antonio has issued a

* Severe Thunderstorm Warning for...
  Southern Caldwell County in south central Texas...
  South central Hays County in south central Texas...
  Guadalupe County in south central Texas...
  Gonzales County in south central Texas...

* Until 1245 AM CDT.

* At 1143 PM CDT, severe thunderstorms were located along a line
  extending from near San Marcos to Kingsbury to near New Berlin,
  moving southeast at 30 mph.

  HAZARD...60 mph wind gusts and nickel size hail.

  SOURCE...Radar indicated.

  IMPACT...Expect damage to roofs, siding, and trees.

* Locations impacted include...
  San Marcos, Seguin, Gonzales, Luling, McQueeney, Nixon, Martindale,
  Kingsbury, Smiley, Staples, Fentress, Palmeto State Park, Geronimo,
  Zorn, Brownsboro, Delhi, Leesville, Joliet, Oak Forest and Belmont.

PRECAUTIONARY/PREPAREDNESS ACTIONS...

For your protection move to an interior room on the lowest floor of a
building.

Large hail, damaging winds, and continuous cloud to ground lightning
are occurring with these storms. Move indoors immediately. Lightning
is one of nature's leading killers. Remember, if you can hear
thunder, you are close enough to be struck by lightning.

Torrential rainfall is occurring with these storms, and may lead to
flash flooding. Do not drive your vehicle through flooded roadways.

&&

LAT...LON 2913 9759 2925 9776 2935 9786 2938 9784
      2938 9794 2947 9807 2969 9798 2986 9803
      2982 9736 2978 9731 2937 9731
TIME...MOT...LOC 0443Z 302DEG 24KT 2984 9798 2966 9784 2946 9807 

HAIL THREAT...RADAR INDICATED
MAX HAIL SIZE...0.88 IN
WIND THREAT...RADAR INDICATED
MAX WIND GUST...60 MPH

$$

BRADY
